### ISSUE TITLE
Support for --log-lib TRANSPORT_FRM option

### ISSUE THREAD

**Issue by kornys** [rh-messaging/cli-java#41]
Please make support for **TRANSPORT_FRM** options to enable proton like frame logs (PN_TRACE_FRM=1).
Other clients like cli-netlite, cli-rhea and cli-proton-python already have support for TRANSPORT_FRM opt.

**Comment by kornys** [comment]
@jdanekrh please if you have time, look at it ASAP, many thanks.

**Comment by jdanekrh** [comment]
@kornys Workaround for qpid-jms, set env variable `PN_TRACE_FRM=1`

other clients (activemq-client and artemis-jms-client) afaik do not have frame logging, but I'd have to investigate that.

**Comment by kornys** [comment]
@jdanekrh what I need is log this on stderr like other clients please

**Comment by jdanekrh** [comment]
In cli-qpid-jms, I cannot give you PN_TRACE_FRM on stderr because qpid-proton-j prints it on stdout, see https://github.com/apache/qpid-proton-j/blob/e7aae9469ac2f45a6de1822d7fe3cd2d4c8a314c/proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java#L1694-L1709. You should ask @gemmellr or @tabish121 and fill a qpid-protoj-j bug in Jira, afaik.

I can put the rest of the logs on stderr if I figure out how to do it in log4j.properties file...

**Comment by kornys** [comment]
@jdanekrh interesting, proton python prints PN_TRACE_FRM on stderr. Ok I will raise an issue on proton-j

**Comment by kornys** [comment]
https://issues.apache.org/jira/browse/PROTON-1797

**Comment by jdanekrh** [comment]
I won't give you PN_TRACE_FRM, but the rest of the logs is redirected to stderr in PR #42
